source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'Populate_Example' do
  pod "Populate", :path => "../"
  pod 'Stack', :path => "../../Stack"
end

target 'Populate_Tests' do
  pod "Populate", :path => "../"  
end
